project_root: /home/ubuntu/galaxy-content-site
server_root: /home/ubuntu/server
web_root: /srv/sites/webapp
venv_root: {{ project_root }}/.venv

nginx_vhost_template: "templates/webapp.conf.tmpl"

certbot_admin_email: c.hyde@qcif.edu.au
certbot_create_if_missing: true
certbot_certs:
  - domains:
    - usegalaxy-au.neoformit.com
certbot_create_standalone_stop_services:
  - nginx
certbot_create_command: "{{ certbot_script }} --standalone --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }} --nginx"

gunicorn:
  web_workers: 4

webapp:
  templates:
    gunicorn:
      src: templates/gunicorn.py.tmpl
      dest: {{ server_root }}/gunicorn.py
    systemd:
      src: templates/webapp.service.tmpl
      dest: /etc/systemd/system/webapp.service
    setup:
      src: templates/setup.sh.tmpl
      dest: {{ server_root }}/setup.sh

  files:
    socket:
      src: files/webapp.socket
      dest: /etc/systemd/system/webapp.socket

  admin_user:
    first_name: admin
    last_name: admin
    email: admin@website.com
    password: secret
