---

# Read vault from secrets.yml:
# admin_email: <str>
# admin_password: <str>
# database_password: <str>
# django_secret_key: <str>
# smtp_password: <str>

# If you don't want SSL certs, just flip this:
certbot_ssl: true
certbot_renew_email: c.hyde@qcif.edu.au

# 4 web workers should be plenty - increase for machines with >4 CPUs
gunicorn:
  web_workers: 4

# Postgres database conf
postgres_db_name: webapp
postgres_db_user: webapp

postgresql_locales:
  - 'en_US.UTF-8'

postgresql_databases:
  - name: "{{ postgres_db_name }}"
    port: 5432

postgresql_users:
  - name: "{{ postgres_db_user }}"
    password: "{{ postgres_db_password }}"
    db: "{{ postgres_db_name }}"

postgres_users_no_log: false

# GMS Webapp configuration
# -----------------------------------------------------------------------------

# Will git clone galaxy-content-site to here
project_root: /home/ubuntu/galaxy-content-site

# This is where service files will be created
server_root: /home/ubuntu/serve

# App will be served from here
web_root: /srv/webapp

# Virtual environment will be created here
venv_root: "{{ project_root }}/.venv"

# Admin user login for the admin portal
admin_user:
  first_name: admin
  last_name: admin
  email: "{{ admin_email }}"
  password: "{{ admin_password }}"

smtp:
  hostname: mail.usegalaxy.org.au
  port: 22
  username: galaxy-australia
  from_address: noreply@genome.edu.au
  to_address: help@genome.edu.au
  use_tls: true

# For error notifications
slack:
  errors:
    api_key: "{{ slack_error_api_key }}"  # secrets.yml
    channel_id: CJVFNFKGD
    mention_user_id: U024MUHM23W
  tools:
    url: "{{ slack_api_url }}"  # secrets.yml
