---
project_root: /home/ubuntu/galaxy-content-site
server_root: /home/ubuntu/server
web_root: /srv/webapp
venv_root: "{{ project_root }}/.venv"

webapp:
  templates:
    - src: "{{ role_path }}/templates/gunicorn.py.j2"
      dest: "{{ server_root }}/gunicorn.py"
    - src: "{{ role_path }}/templates/webapp.service.j2"
      dest: /etc/systemd/system/webapp.service
    - src: "{{ role_path }}/templates/setup.sh.j2"
      dest: "{{ server_root }}/setup.sh"
    - src: "{{ role_path }}/templates/nginx.vhost.j2"
      dest: "/etc/nginx/sites-available/{{ inventory_hostname }}.conf"
    - src: "{{ role_path }}/templates/.env.j2"
      dest: "{{ project_root }}/.env"
    - src: "{{ role_path }}/templates/update.sh.j2"
      dest: "/home/ubuntu/update.sh"

  files:
    - src: "{{ role_path }}/files/webapp.socket"
      dest: /etc/systemd/system/webapp.socket

certbot_ssl: true

gunicorn:
  web_workers: 4
